# eslint yml/sort-keys: 'error'

catalog:
  '@vue/compiler-core': ^3.4.31
  '@vue/compiler-dom': ^3.4.31
  '@vue/compiler-sfc': ^3.4.31
  '@vue/language-core': 2.0.26
  '@vue/shared': ^3.4.31
  unplugin: ^1.11.0
  vite: ^5.3.3
  vue: ^3.4.31
  vue-tsc: 2.0.26
packages:
  - packages/*
  - playground/*
  - '!playground/nuxt'
  - docs
