# eslint yml/sort-keys: 'error'

catalog:
  '@vue/compiler-core': ^3.5.5
  '@vue/compiler-dom': ^3.5.5
  '@vue/compiler-sfc': ^3.5.5
  '@vue/language-core': 2.1.6
  '@vue/reactivity': ^3.5.5
  '@vue/runtime-core': ^3.5.5
  '@vue/runtime-dom': ^3.5.5
  '@vue/shared': ^3.5.5
  typescript: ^5.6.2
  unplugin: ^1.14.1
  vite: ^5.4.5
  vue: ^3.5.5
  vue-tsc: 2.1.6
packages:
  - packages/*
  - playground/*
  - '!playground/nuxt'
  - docs
