# eslint yml/sort-keys: 'error'

catalog:
  '@vue/compiler-core': ^3.5.3
  '@vue/compiler-dom': ^3.5.3
  '@vue/compiler-sfc': ^3.5.3
  '@vue/language-core': 2.1.6
  '@vue/reactivity': ^3.5.3
  '@vue/runtime-core': ^3.5.3
  '@vue/runtime-dom': ^3.5.3
  '@vue/shared': ^3.5.3
  typescript: 5.6.1-rc
  unplugin: ^1.14.0
  vite: ^5.4.3
  vue: ^3.5.3
  vue-tsc: 2.1.6
packages:
  - packages/*
  - playground/*
  - '!playground/nuxt'
  - docs
