# eslint yml/sort-keys: 'error'

catalog:
  '@vue/compiler-core': ^3.4.33
  '@vue/compiler-dom': ^3.4.33
  '@vue/compiler-sfc': ^3.4.33
  '@vue/language-core': 2.0.28
  '@vue/shared': ^3.4.33
  unplugin: ^1.11.0
  vite: ^5.3.4
  vue: ^3.4.33
  vue-tsc: 2.0.28
packages:
  - packages/*
  - playground/*
  - '!playground/nuxt'
  - docs
